### ISSUE TITLE
Mismatch between bid files and dudetailsummary

### ISSUE THREAD

**Issue by mlee94** [UNSW-CEEM/nempy#22]
Getting an error when running the solve for an old datetime. 

`unit_bid_limit` is invalid against the `unit_info`. 

Could the mms table `DUDETAILSUMMARY` not be bringing back the list of DUID's that submitted a volume/price bid for this datetime. The following DUID's are missing: ['ADPBA1G', 'ADPBA1L', 'BOWWBA1G', 'BOWWBA1L', 'BULBESG1',
       'BULBESL1', 'DRXNDA01', 'DRXVDJ01', 'VBBG1', 'VBBL1', 'WALGRVG1',
       'WALGRVL1', 'WANDBG1', 'WANDBL1']

Can you please try the repro below to check you receive the same error (adjusted for your db paths):

```

import sqlite3
from datetime import datetime, timedelta
import random
import pandas as pd
from nempy import markets
from nempy.historical_inputs import loaders, mms_db, \
    xml_cache, units, demand, interconnectors, constraints, rhs_calculator
from nempy.help_functions.helper_functions import update_rhs_values

con = sqlite3.connect('D:/nempy_2021/historical_mms.db')
mms_db_manager = mms_db.DBManager(connection=con)

xml_cache_manager = xml_cache.XMLCacheManager('D:/nempy_2021/xml_cache')

interval = '2021/12/08 15:30:00'
print(str(c) + ' ' + str(interval))
raw_inputs_loader.set_interval(interval)
unit_inputs = units.UnitData(raw_inputs_loader)
interconnector_inputs = interconnectors.InterconnectorData(raw_inputs_loader)
constraint_inputs = constraints.ConstraintData(raw_inputs_loader)
demand_inputs = demand.DemandData(raw_inputs_loader)
rhs_calculation_engine = rhs_calculator.RHSCalc(xml_cache_manager)

unit_info = unit_inputs.get_unit_info()
market = markets.SpotMarket(market_regions=['QLD1', 'NSW1', 'VIC1',
                                            'SA1', 'TAS1'],
                            unit_info=unit_info)

# Set bids
volume_bids, price_bids = unit_inputs.get_processed_bids()
market.set_unit_volume_bids(volume_bids)
market.set_unit_price_bids(price_bids)

# Set bid in capacity limits
unit_bid_limit = unit_inputs.get_unit_bid_availability()
market.set_unit_bid_capacity_constraints(unit_bid_limit)
```
<details>
<summary>Full Traceback:</summary>
Traceback (most recent call last):
  File "/opt/pycharm-2022.3.1/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 23, in <module>
  File "/home/michael/Documents/Gitrepos/nempy/nempy/markets.py", line 467, in set_unit_bid_capacity_constraints
    self._validate_unit_limits(unit_limits)
  File "/home/michael/Documents/Gitrepos/nempy/nempy/markets.py", line 477, in _validate_unit_limits
    schema.validate(unit_limits)
  File "/home/michael/Documents/Gitrepos/nempy/nempy/spot_markert_backend/dataframe_validator.py", line 29, in validate
    self.columns[col].validate(df[col])
  File "/home/michael/Documents/Gitrepos/nempy/nempy/spot_markert_backend/dataframe_validator.py", line 62, in validate
    self._check_allowed_values(series)
  File "/home/michael/Documents/Gitrepos/nempy/nempy/spot_markert_backend/dataframe_validator.py", line 79, in _check_allowed_values
    raise ColumnValues("The column {} can only contain the values {}.".format(self.name, self.allowed_values))
nempy.spot_markert_backend.dataframe_validator.ColumnValues: The column unit can only contain the values 0        AGLHAL
1       AGLNOW1
2      AGLSITA1
3        AGLSOM
4       ANGAST1
         ...   
537       YWNL1
538       YWPS1
539       YWPS2
540       YWPS3
541       YWPS4
Name: unit, Length: 542, dtype: object.
</details>

**Comment by mlee94** [comment]
Think I found a bug in this code - one second. Checking something.

**Comment by mlee94** [comment]
Closing issue, as it's a bug in the code, will create a PR
